--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: API_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."API_category" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public."API_category" OWNER TO postgres;

--
-- Name: API_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."API_category" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."API_category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: API_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."API_product" (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    brand character varying(100) NOT NULL,
    size character varying(50) NOT NULL,
    quantity integer NOT NULL,
    status character varying(50) NOT NULL,
    price numeric(8,2) NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public."API_product" OWNER TO postgres;

--
-- Name: API_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."API_product" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."API_product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: API_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."API_category" (id, name) FROM stdin;
22	Chemisiers et blouses
23	Vestes
24	Sweat
25	Manteaux
26	Accessoires
\.


--
-- Data for Name: API_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."API_product" (id, name, brand, size, quantity, status, price, category_id) FROM stdin;
13	Casquette	Nike	3	1	Accepté	10.00	26
14	Casquette rose	Adidas	3	1	Accepté	10.00	26
15	Veste en jean	Wrangler	30	1	Accepté	50.00	23
16	Chemise a carreaux	Jules	M	1	Accepté	20.00	22
17	Manteaux a fourures	North Face	XL	1	En attente	120.00	26
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	API	0001_initial	2023-05-22 15:00:22.223896+02
2	API	0002_category_product_delete_test	2023-05-22 15:00:22.332799+02
\.


--
-- Name: API_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."API_category_id_seq"', 26, true);


--
-- Name: API_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."API_product_id_seq"', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 2, true);


--
-- Name: API_category API_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."API_category"
    ADD CONSTRAINT "API_category_pkey" PRIMARY KEY (id);


--
-- Name: API_product API_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."API_product"
    ADD CONSTRAINT "API_product_pkey" PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: API_product_category_id_a02ddc98; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "API_product_category_id_a02ddc98" ON public."API_product" USING btree (category_id);


--
-- Name: API_product API_product_category_id_a02ddc98_fk_API_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."API_product"
    ADD CONSTRAINT "API_product_category_id_a02ddc98_fk_API_category_id" FOREIGN KEY (category_id) REFERENCES public."API_category"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

